#!/bin/sh

# Setup
## Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

## Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"
## sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
  alias $command="sudo $command"
done
unset command

# Luke's Aliases 
## Verbosity and settings that you pretty much just always are going to want.
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  bc="bc -ql" \
  mkd="mkdir -pv" \
  yt="yt-dlp --embed-metadata -i" \
  yta="yt -x -f bestaudio/best" \
  ffmpeg="ffmpeg -hide_banner" \
  xclip="xclip -se c" \
  setkey="setxkbmap -layout br"

## Colorize commands when possible.
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi" \
  ip="ip -color=auto"

## These common commands are just too long! Abbreviate them.
alias \
  ka="killall" \
  g="git" \
  trem="transmission-remote" \
  YT="youtube-viewer" \
  sdn="shutdown -h now" \
  e="$EDITOR" \
  v="$EDITOR" \
  p="pacman" \
  xi="sudo xbps-install" \
  xr="sudo xbps-remove -R" \
  xq="xbps-query" \
  z="zathura"

alias \
  lf="lfub" \
  magit="nvim -c MagitOnly" \
  ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
  weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"

# User created 

# Functions 
install_jq() {
    if ! command -v jq> /dev/null>&1; then
        echo "jq not found. Installing jq..."
        yay jq
    fi
}

get_github_username() {
    # Run 'gh api user' to get the GitHub username
    username=$(gh api user --jq '.login' -H 'Accept: application/vnd.github.v3+json')

    # Return the username
    echo "$username" | tr -d '"'
}

get_pr_list_for_authenticated_user() {
    # Install jq if not already installed
    install_jq

    # Get the GitHub username using the previously defined function
    username=$(get_github_username)

    # Call 'gh pr list' for the authenticated user
    gh pr list -s all -A "$username"
}

## General 
alias \
  agora="date '+%Y-%m-%d_%Hh%Mm%Ss'" \
  cls="clear && ls -At1hN --color=auto --group-directories-first" \
  docs="cd $HOME/zettelkasten/ && $EDITOR ." \
  exa="exa --icons -1 --group-directories-first -s=extension -rs modified" \
  clexa="clear && exa" \
  fd="fd -H" \
  fecha="pomo s -t \"#ritual_fechamento\" -p 1 \"Ritual de fechamento\"" \
  hj="cd $HOME/HISTORICO/ATIVO/`date '+%Y'`/`date '+%m'` && $HOME/.local/bin/hj.lua" \
  kamed="libreoffice $HOME/Ricanda/KAMAL/KAMAL_REMEDIOS.ods" \
  kamal="cd $HOME/Ricanda/KAMAL && exa" \
  lsa="ls -At1hN --color=auto --group-directories-first" \
  mapa="libreoffice $HOME/HISTORICO/ATIVO/PROJETOS/RICARDO/mapa_da_ignorancia/mapa_da_ignorancia/mapa_da_ignorancia.ods" \
  meta="cd $HOME/Ricanda/meta/ && $EDITOR ." \
  pl="pomo l --assend -n 5" \
  pomobackup="pomo l --json > pomo_hist_\`date '+%Y-%m-%d_%Hh%Mm%Ss'\`.json && mv *.json /home/ricar/Ricanda/HISTORICO/pomo" \
  prnt="import \`date '+%Y-%m-%d_%Hh%Mm%Ss'\`.jpg" \
  procsel="$HOME/HISTORICO/ATIVO/PROJETOS/RICARDO/proc_seletivo/ && ls -A1" \
  p10="pomo l --assend -n 10" \
  renameall="$HOME/.local/bin/rename_multiple" \
  repo="cd ~/source/repos/" \
  steam="flatpak run com.valvesoftware.Steam" \
  uniproj="$HOME/HISTORICO/ATIVO/PROJETOS/UNILASALLE" \
  unrar="unrar-free" \
  wall="set-wallpaper" \
  w2k="$HOME/.local/bin/styli.sh -r earthporn -w 3840 -h 1080" \
  week="sc-im $HOME/weeks/\`date '+%V'\`.sc" \
  nweek="sc-im $HOME/weeks/\`echo $(($(date '+%V')+1))\`.sc" \
  weeks="cd $HOME/weeks" \
  wh="cd /mnt/c/Users/ricar/" \
  xd="$HOME/.config/xrandr/dual_landscape_vertical_perspectiva.sh" \
  xs="$HOME/.config/xrandr/single.sh" \
  xu="$HOME/.config/xrandr/dual_ultrawide.sh" \
  du="du -h" \
  hist="$EDITOR $HOME/.cache/zsh/history" \
  music="sudo apple-music-for-linux" \
  cp-gpt="echo 'window.clear();Array.from(document.getElementsByClassName(\"text-base\")).forEach((x)=>console.log(x.textContent));'|xclip" \
  prospect="cd $HOME/HISTORICO/ATIVO/PROJETOS/RICARDO/proc_seletivo/_oportunidades && clear && exa" \
  prospectb="cd $HOME/HISTORICO/ATIVO/PROJETOS/RICARDO/proc_seletivo/_oportunidades && clear && libreoffice ./oportunidades.ods" \
  mupdf="/bin/mupdf -I" \
  pumldoc="$HOME/.local/bin/pumldoc.lua" \
  manuais="cd $HOME/Ricanda/manuais/ && exa" \
  vmon="vm_start" \
  vmoff="vm_shutdown" \
  calcurse="calcurse -D $HOME/calcurse/ && clexa $HOME/calcurse -a" \
  rg="rg -.i" \
  vncs="x0vncserver -rfbauth ~/.vnc/passwd &  \ # start tigervnc, to allow remote connections" \
  rarandr="arandr && vncs" \
  connecthost="ssh $USER@$(cat $HOME/Ricanda/hostip)" \
  vncview="vncviewer $(cat $HOME/Ricanda/hostip):5900" \
  wdisplay="xrandr -s 1920x1080" \
  uwdisplay="xrandr -s 2560x1080" \
  bys="cd $HOME/projetos/bys/ && clexa -a" \

## Games
STEAM_GAME="steam steam://rungameid"
alias \
  sod="$STEAM_GAME/986130" \
  valheim="$STEAM_GAME/892970" \
  et2="$STEAM_GAME/227300" \
  zomboid="$STEAM_GAME/108600" \
  rimworld="$STEAM_GAME/294100" \

## Coding 
alias \
  sourcez="source $HOME/.config/zsh/.zshrc" \
  tsdbg="google-chrome-stable --remote-debugging-port=9222 http://localhost:4200" \
  code="vscodium" \
  ### Git 
  alias \
    gd='git diff -w' \
    gl='git log --all --graph --oneline --decorate' \
    gs='git status' \
    ga='git add . && git status'
  ### GitHub CLI
  alias \
    prl=get_pr_list_for_authenticated_user \
    pr='gh pr view -c' \
