#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Ensures notebook display off if it's folded
folded-notebook # https://github.com/ricardobossan/folded-notebook

xrandr --dpi 96 # Set DPI. User may want to use a larger number for larger screens.
#setbg &			# set the background with the `setbg` script


# shellcheck disable=2086
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps & # run the remaps script, switching caps/esc and more; check it for more info
setxkbmap -layout br
syncthing --no-browser &
redshift -l -22.9:-43.0 -t 6500:2500 -b 1:0.5 & # Apply blue-light filter, based on lat/long.
transmission-daemon & # start torrent service
pipewire & # sometimes, when leaving dwm and comming back, pipewre doesn't autostart. If it's already started, it just does nothing.

if ! $(pgrep -nf valheim_server.x86_64); then
  $HOME/valheim-server/valheim.sh
fi

autostart="mpd xcompmgr dunst unclutter pipewire"

# Starts ssh-agent
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

# Define random wallpaper using styli.sh
set-wallpaper # https://github.com/ricardobossan/set-wallpaper

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

# :TODO Unsafe! find a way to mask the output file path
#ip a show eno1 | grep -oP 'inet \K[\d.]+' | head -n 1 > $HOME/Ricanda/hostip
if hostnamectl | grep -qi 'chassis.*desktop' ; then
    ip a show eno1 | grep -oP 'inet \K[\d.]+' | head -n 1 > $HOME/Ricanda/hostip
    x0vncserver -rfbauth ~/.vnc/passwd -Geometry 1920x1080+0+0 & # start tigervnc, to allow remote connections
  else
   connecthost
fi
